services:
  - type: web
    name: telegram-pdf-bot
    env: python
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7511704960:AAH-rIBOQkhzYvTVOp2tiodxzK3vp8GUiYM
      - key: WEBHOOK_URL
        value: https://telegram-pdf-bot-tqm5.onrender.com
