services:
  - type: web
    name: telegram-pdf-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: WEBHOOK_URL
        value: "https://telegram-pdf-bot-1f5c.onrender.com/telegram" # Исправьте домен, если нужно
      - key: PYTHON_VERSION
        value: "3.10"
    runtimeEnvVars:
      - key: PORT
        value: "8080"
