services:
  - type: web
    name: telegram-pdf-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false  # Установи вручную в Render Dashboard
      - key: ADMIN_ID
        sync: false  # Тоже установи вручную
      - key: WEBHOOK_URL
        value: "https://telegram-pdf-bot-1f5c.onrender.com/telegram"
    runtimeEnvVars:
      - key: PORT
        value: "8080"
