services:
  - type: web
    name: telegram-pdf-bot
    env: python
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: your-telegram-bot-token-here
      - key: WEBHOOK_URL
        value: https://your-app-name.onrender.com
